### ISSUE TITLE
Develop a system for standardizing contributor names

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-campaign-browser#173]
Ala [this](https://github.com/cjdd3b/fec-standardizer)

**Comment by miketahani** [comment]
Just saw this on NICAR-L, might be relevant if you're willing to pull in a third-party dependency.

https://github.com/datamade/probablepeople

**Comment by palewire** [comment]
We're open to tools like that but in addition to solutions to tricky problems, like parsing names, we also need some just of framework or superstructure on top of our models that makes it happen. That's what we're looking for here.

**Comment by JoeGermuska** [comment]
I've always figured that a step like this requires human review. Is that part of what you mean by "framework" or "superstructure"? Or do you think that something automated could be good-enough?

**Comment by palewire** [comment]
Sure, that and whatever intermediary steps will need to go into the process. This area is @anthonyjpesce's interest so he knows more about it than me. 

Here are things that jump to my mind:

* Since there is no canonical donor UID, we'll need to work out what fields taken together we want to treat as defining "uniqueness."
* We'll then need to script a routine that pulls that unique list from the raw data
* Then some ingestion routine that pulls that list into the standardization system
* We'll then need to develop the actual g.d. system for combining mutations, which should probably have some kind of supervised sample or transparent method we can document, tweak, improve, etc.
* Then we need some way to reconcile the outputs of that back to the line-item data to be used in analysis and presentation
* Then the whole thing has to be automated so it can update on a rolling basis as new data arrives

I doubt all that stuff needs to ultimately live in this repository. But one thing I think this repo can work our right away is how to write the proper database query to pull out the raw materials necessary to do the sexy stuff.

**Comment by rkiddy** [comment]
I have started to do something here. I will have to put together a pull request when it is workable. This is not yet very efficient. And should this actually be in the browser project and not the raw-data project?

My approach so far has been to:

1) Create a names table. Right now this has the columns:
```
id - int, primary key
ext_table - varchar, the name of the table from which the name comes
ext_pref - varchar, the prefix of the columns, "filer" or "intr" or ...
ext_pk - int, the pk in the table
naml - varchar
namf - varchar
nams - varchar
namt - varchar
name - varchar
```
Example rows are:
```
*************************** 1. row ***************************
        id: 40010010
    ext_pk: 2605911
 ext_table: EXPN_CD
ext_prefix: PAYEE
      naml: CompleteCampaigns.com a Div. of Aristotle International Inc.
      namf: 
      nams: 
      namt: 
      name: CompleteCampaigns.com a Div. of Aristotle International Inc.
*************************** 2. row ***************************
        id: 1
    ext_pk: 1
 ext_table: CVR2_LOBBY_DISCLOSURE_CD
ext_prefix: ENTY
      naml: Hall
      namf: Joan
      nams: 
      namt: Ms.
      name: Ms. Joan Hall
```
I am creating the name column by a concat of namt, namf, naml and nams and then I trim it and replace multiple spaces with one space. And wow, does this suck up time and cpu cycles.

I think it may be worth adding an 'is_person' column of some kind and using probablepeople to fill that in. That then can be fed to a de-duplicator. I have looked at https://github.com/datamade/dedupe but it is a lot to figure out. For one thing, dedupe may already use probablepeople.

I then think we need an "identity" column. As a first step, completely identical entries in the name table can be coalesced here. For example, there would be one "Ms. Joan Hall" and all of the "Ms. Joan Hall" entries in the name table, and ultimately in the other table, would point to this.

There are more things to bring up, but this is becoming too much at once.
